import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { ArrowRight, BrainCircuit, CalendarDays, CheckCircle2, FileText, Layers3, MessageSquareText, Sparkles, Zap } from "lucide-react";
import React from "react";
import { useLocation } from "wouter";

const features = [
  { icon: MessageSquareText, title: "Study with an AI that understands context", text: "Turn unclear concepts into useful explanations, revision prompts, and focused next steps." },
  { icon: CalendarDays, title: "Plan the work that matters", text: "Transform subjects, deadlines, and available hours into a study rhythm you can actually follow." },
  { icon: FileText, title: "Make every document searchable", text: "Bring PDFs, DOCX, and text notes into one workspace for summaries, questions, and clarity." },
  { icon: Layers3, title: "Build recall, not just notes", text: "Generate quizzes and flashcards, then keep a record of how your understanding is progressing." },
];

export default function MarketingHome() {
  const { isAuthenticated } = useAuth();
  const [, navigate] = useLocation();
  const enter = () => isAuthenticated ? navigate("/dashboard") : startLogin();

  return (
    <div className="min-h-screen overflow-hidden bg-[#080a1b] text-white nova-marketing">
      <div className="nova-aurora nova-aurora-one" /><div className="nova-aurora nova-aurora-two" />
      <header className="container relative z-10 flex items-center justify-between py-6">
        <button className="flex items-center gap-3" onClick={() => navigate("/")}><span className="nova-mark"><Sparkles size={18} /></span><span className="font-semibold tracking-tight">NovaMind <em className="not-italic text-cyan-300">AI</em></span></button>
        <nav className="hidden items-center gap-7 text-sm text-slate-300 md:flex"><a href="#features">Features</a><a href="#workflow">How it works</a><button onClick={enter}>AI Assistant</button></nav>
        <div className="flex items-center gap-3"><button onClick={enter} className="hidden text-sm text-slate-300 sm:block">Sign in</button><button onClick={enter} className="nova-button nova-button-small">Get started <ArrowRight size={15} /></button></div>
      </header>
      <main>
        <section className="container relative z-10 grid gap-12 pb-24 pt-16 lg:grid-cols-[1.03fr_.97fr] lg:items-center lg:pb-32 lg:pt-24">
          <div className="max-w-2xl"><div className="nova-eyebrow"><Sparkles size={14} /> Built for deep work, not busywork</div><h1 className="mt-7 text-balance text-5xl font-semibold leading-[1.02] tracking-[-0.055em] sm:text-6xl lg:text-7xl">Think smarter.<br /><span className="nova-gradient-text">Learn faster.</span><br />Stay ahead.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">NovaMind AI brings your tasks, study material, plans, and progress into one intelligent workspace—so every session moves you forward.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={enter} className="nova-button">Start your workspace <ArrowRight size={17} /></button><a href="#features" className="nova-button-secondary">Explore the system</a></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-300"><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-cyan-300" /> Personal, protected workspace</span><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-cyan-300" /> AI support when you need it</span></div></div>
          <div className="nova-dashboard-preview"><div className="nova-learning-loop" aria-hidden="true"><i /><i /><i /><i /></div><div className="nova-preview-header"><span className="flex items-center gap-2 text-sm font-medium"><span className="nova-mark h-7 w-7"><Sparkles size={13} /></span> NovaMind</span><span className="h-2 w-2 rounded-full bg-cyan-300 shadow-[0_0_16px_#67e8f9]" /></div><div className="relative p-5"><div className="flex items-end justify-between"><div><p className="text-xs text-slate-400">Tuesday, 08:45</p><h2 className="mt-1 text-xl font-semibold">Good morning, Alex.</h2></div><div className="rounded-xl bg-violet-500/15 px-3 py-2 text-xs text-violet-200">3 day streak</div></div><div className="mt-5 grid grid-cols-3 gap-3"><MiniMetric label="Study time" value="4.5h" accent="cyan" /><MiniMetric label="On track" value="82%" accent="violet" /><MiniMetric label="Tasks" value="7/9" accent="blue" /></div><div className="mt-4 grid gap-4 sm:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-white/8 bg-white/[.035] p-4"><div className="flex items-center justify-between"><p className="text-xs text-slate-400">This week</p><span className="text-xs text-cyan-300">+24%</span></div><div className="mt-6 flex h-24 items-end gap-2">{[38, 56, 40, 78, 62, 91, 72].map((height, index) => <span key={index} className="flex-1 rounded-t-lg bg-gradient-to-t from-violet-500 to-cyan-300/90" style={{ height: `${height}%`, opacity: index === 5 ? 1 : .55 }} />)}</div><p className="mt-3 text-xs text-slate-400">Focused study rhythm</p></div><div className="rounded-2xl border border-white/8 bg-gradient-to-br from-violet-500/25 to-cyan-400/10 p-4"><Zap size={18} className="text-cyan-200" /><p className="mt-3 text-sm font-medium leading-5">Next best move</p><p className="mt-1 text-xs leading-5 text-slate-300">Review DBMS normalization for 45 minutes.</p></div></div><div className="mt-4 flex items-center gap-3 rounded-2xl border border-white/8 bg-white/[.035] p-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-400/15 text-cyan-200"><BrainCircuit size={18} /></span><div className="flex-1"><p className="text-xs text-slate-400">NovaMind AI</p><p className="text-sm text-slate-200">Ready to turn your notes into a revision plan.</p></div><ArrowRight size={16} className="text-cyan-200" /></div></div></div>
        </section>
        <section id="features" className="container relative z-10 py-24"><div className="max-w-2xl"><div className="nova-eyebrow"><BrainCircuit size={14} /> One place for the full learning loop</div><h2 className="mt-5 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">More clarity. Less friction. Better recall.</h2><p className="mt-5 text-lg leading-8 text-slate-300">NovaMind connects the moments that usually sit in separate tools: planning, material, active recall, and reflection.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2">{features.map((feature, index) => <article className="nova-feature-card" key={feature.title}><span className="nova-feature-icon"><feature.icon size={21} /></span><span className="text-xs text-cyan-300">0{index + 1}</span><h3 className="mt-6 text-xl font-medium">{feature.title}</h3><p className="mt-3 leading-7 text-slate-400">{feature.text}</p><button onClick={enter} className="mt-6 flex items-center gap-2 text-sm font-medium text-violet-200 transition hover:text-cyan-200">Explore workspace <ArrowRight size={15} /></button></article>)}</div></section>
        <section id="workflow" className="container relative z-10 py-24"><div className="nova-workflow rounded-[2rem] p-7 sm:p-10 lg:p-14"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-sm font-medium text-cyan-300">The NovaMind method</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em]">A quieter system for ambitious learners.</h2><p className="mt-5 leading-7 text-slate-300">Capture what matters, let AI shape a plan, then learn through active recall. NovaMind keeps the signal visible—from today’s next step to long-term progress.</p><button onClick={enter} className="nova-button mt-8">Build your study system <ArrowRight size={16} /></button></div><div className="space-y-3">{[["01", "Bring your workload together", "Tasks, notes, documents, exams, and study sessions all live in one focused view."], ["02", "Turn material into momentum", "Generate a plan, summary, quiz, or flashcard set from the context you already have."], ["03", "See what is actually improving", "Use your learning data to protect your attention and make better decisions next time."]].map(([step, title, text]) => <div className="flex gap-5 rounded-2xl border border-white/8 bg-black/10 p-5" key={step}><span className="text-sm font-semibold text-violet-300">{step}</span><div><h3 className="font-medium">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-400">{text}</p></div></div>)}</div></div></div></section>
        <section className="container relative z-10 pb-12 pt-12"><div className="rounded-[2rem] border border-cyan-200/10 bg-gradient-to-br from-violet-500/25 via-indigo-500/15 to-cyan-400/15 px-7 py-14 text-center sm:px-12"><p className="text-sm font-medium text-cyan-200">Ready when you are</p><h2 className="mx-auto mt-4 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Give your next study session a better starting point.</h2><button onClick={enter} className="nova-button mt-8">Open NovaMind AI <ArrowRight size={16} /></button></div></section>
      </main>
      <footer className="container relative z-10 flex flex-col gap-4 py-9 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} NovaMind AI. A focused learning companion.</p><p>Made for intentional study.</p></footer>
    </div>
  );
}

function MiniMetric({ label, value, accent }: { label: string; value: string; accent: string }) { return <div className="rounded-2xl border border-white/8 bg-white/[.035] p-3"><span className={`block h-1 w-7 rounded-full bg-${accent === "cyan" ? "cyan" : accent === "violet" ? "violet" : "blue"}-300`} /><p className="mt-3 text-xs text-slate-400">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
